program simulation
    use, intrinsic :: iso_fortran_env, only: dp => real64
    use forces_mod
    use utils_mod
    use io_mod
    use ui_mod
    use var_mod
    implicit none

    type(parameters) :: params
    type(particles)  :: part
    type(system_g)   :: sys

    integer  :: step
    real(dp) :: temp

    !-------------------- Initialization --------------------!
    call random_seed()

    call init_params(params)
    call get_command_argument(1, params%outdir)
    
    if (len_trim(params%outdir) == 0) then
        error stop "simulation: informe o diretorio de saida"
    end if

    call read_nml(sys, part, params)

    call init_system(sys)
    call alloc_particles(part, sys)
    
    call init_verlet_list(sys, part)

    ! Read initial state generated by init_conf
    call read_config(sys, part, params%init_filename)
    call read_part_file(part, sys, params%part_filename)

    call validate_configuration(part%positions, part%radius, sys%box)

    call initialize(sys, params, part, dt)

    call verlet_list(part%positions, sys%box, sys%r_list, sys%list, sys%point, sys%r_save)

    call forces(part%positions, sys%box, part%radius, part%charges, &
        eps, sys%bjerrum, sys%kappa, sys%r_cut_dlvo, &
        sys%list, sys%point, sys%total_forces, sys%total_potential)

    if (.not. all(part%velocities == part%velocities)) error stop "NaN detectado"

    !-------------------- Main loop --------------------!
    do step = 1, params%max_steps

        if (check_list(part%positions, sys%r_save, sys%box, sys%skin)) then
            call verlet_list(part%positions, sys%box, sys%r_list, sys%list, sys%point, sys%r_save)
        end if

        call u2_propagator(dt/2.0_dp, part%velocities, sys%total_forces, part%masses)
        call langevin_step(dt/2.0_dp, part%velocities, part%masses, sys%gamma, sys%temp_target)
        call u1_propagator(dt, part%positions, part%velocities, sys%box)

        call forces(part%positions, sys%box, part%radius, part%charges, &
            eps, sys%bjerrum, sys%kappa, sys%r_cut_dlvo, &
            sys%list, sys%point, sys%total_forces, sys%total_potential)

        call langevin_step(dt/2.0_dp, part%velocities, part%masses, sys%gamma, sys%temp_target)
        call u2_propagator(dt/2.0_dp, part%velocities, sys%total_forces, part%masses)

        if (.not. all(part%velocities == part%velocities)) error stop "NaN detectado"

        if (mod(step, 100) == 0) then
            call compute_observables(part%masses, part%velocities, sys%g, sys%total_potential, sys%total_energy, temp)
            call write_pdb(sys, part, params%outdir)
            call write_log(sys, part, params%outdir, step, temp, params%is_first)
            call write_out(step, sys%total_energy, temp)
            params%is_first = .false.
        end if

        call check_interruption(params%outdir, params%interrupt)

        if (params%interrupt .or. step == params%max_steps) then
            call write_final_config(sys, part, params%outdir)
            exit
        end if

    end do

    !-------------------- Finalization --------------------!
    call dealloc_particles(part)
    call end_system(sys)

end program simulation